apiVersion: v1
kind: Pod
metadata:
  name: myapp1-pod
  labels:
    app: myapp1
spec:
  containers:
  - name: myapp1-container
    image: prcek/k8stestdocker
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 128Mi
    env:
      - name: APP_NAME
        value: "App1"